import torch
import torch.nn.functional as F
from math import exp


def l1_loss(input, target):
    """L1 Loss"""
    return F.l1_loss(input, target)


def ssim_loss(input, target, window_size=11, sigma=1.5, size_average=True):
    """Structural Similarity Index (SSIM) Loss"""
    channel = input.size()[1]
    window = create_window(window_size, channel, sigma)
    if input.is_cuda:
        window = window.cuda(input.get_device())
    window = window.type_as(input)

    return 1 - _ssim(input, target, window, window_size, channel, size_average)


def total_variation_loss(mask):
    """Total Variation Loss for Mask Regularization"""
    diff_x = mask[:, :, :, :-1] - mask[:, :, :, 1:]
    diff_y = mask[:, :, :-1, :] - mask[:, :, 1:, :]
    tv_loss = torch.sum(torch.abs(diff_x)) + torch.sum(torch.abs(diff_y))
    return tv_loss / mask.numel()


def combined_loss(dehazed_images, clear_images, masks, alpha=0.84, beta=0.16, gamma=0.01):
    """
    Combined Dehazing Loss with Mask Regularization

    :param dehazed_images: Predicted dehazed images from the model [B, 3, H, W]
    :param clear_images: Ground truth clear images [B, 3, H, W]
    :param masks: Compensation masks generated by LACA [B, 1, H, W]
    :param alpha: Weight for L1 loss
    :param beta: Weight for SSIM loss
    :param gamma: Weight for TV loss on masks
    """
    l1 = l1_loss(dehazed_images, clear_images)
    ssim = ssim_loss(dehazed_images, clear_images)
    tv = total_variation_loss(masks)

    return alpha * l1 + beta * ssim + gamma * tv


def create_window(window_size, channel, sigma):
    """Helper function to create Gaussian window for SSIM calculation"""
    gauss = torch.Tensor([exp(-(x - window_size // 2) ** 2 / float(2 * sigma ** 2)) for x in range(window_size)])
    gauss = gauss / gauss.sum()
    _1D_window = gauss.unsqueeze(1)
    _2D_window = _1D_window.mm(_1D_window.t()).float().unsqueeze(0).unsqueeze(0)
    window = _2D_window.expand(channel, 1, window_size, window_size).contiguous()
    return window


def _ssim(img1, img2, window, window_size, channel, size_average=True):
    """Calculate SSIM"""
    mu1 = F.conv2d(img1, window, padding=window_size // 2, groups=channel)
    mu2 = F.conv2d(img2, window, padding=window_size // 2, groups=channel)

    mu1_sq = mu1.pow(2)
    mu2_sq = mu2.pow(2)
    mu1_mu2 = mu1 * mu2

    sigma1_sq = F.conv2d(img1 * img1, window, padding=window_size // 2, groups=channel) - mu1_sq
    sigma2_sq = F.conv2d(img2 * img2, window, padding=window_size // 2, groups=channel) - mu2_sq
    sigma12 = F.conv2d(img1 * img2, window, padding=window_size // 2, groups=channel) - mu1_mu2

    C1 = 0.01 ** 2
    C2 = 0.03 ** 2

    ssim_map = ((2 * mu1_mu2 + C1) * (2 * sigma12 + C2)) / ((mu1_sq + mu2_sq + C1) * (sigma1_sq + sigma2_sq + C2))

    if size_average:
        return ssim_map.mean()
    else:
        return ssim_map.mean(1).mean(1).mean(1)